config/routes.rb
Rails.application.routes.draw do
  get '/' => "home#index"
  resources :orders
  resources :categories
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
class Order < ApplicationRecord
    validates :email, presence: true,format: { with: URI::MailTo::EMAIL_REGEXP }

    def self.show_all
        find_by_sql("select orders.* , GROUP_CONCAT(items.name || ' - ' || cast(order_details.quantity as varchar) || ' portion / Rp.' || cast(order_details.price as varchar), ' | '  ) as detail from orders left join order_details on orders.id = order_details.order_id left join items on items.id = order_details.item_id group by orders.id ")
    end

    def self.show_all_by_email(email)
        find_by_sql("select orders.* , GROUP_CONCAT(items.name || ' - ' || cast(order_details.quantity as varchar) || ' portion / Rp.' || cast(order_details.price as varchar), ' | '  ) as detail from orders left join order_details on orders.id = order_details.order_id left join items on items.id = order_details.item_id where orders.email = '#{email}' group by orders.id ")
    end

    def self.show_all_by_today(date)
        find_by_sql("select orders.* , GROUP_CONCAT(items.name || ' - ' || cast(order_details.quantity as varchar) || ' portion / Rp.' || cast(order_details.price as varchar), ' | '  ) as detail from orders left join order_details on orders.id = order_details.order_id left join items on items.id = order_details.item_id where DATE(orders.created_at) = '#{date}' group by orders.id ")
    end

    def self.show_all_by_total_price(total,sign)
        find_by_sql("select orders.* , GROUP_CONCAT(items.name || ' - ' || cast(order_details.quantity as varchar) || ' portion / Rp.' || cast(order_details.price as varchar), ' | '  ) as detail from orders left join order_details on orders.id = order_details.order_id left join items on items.id = order_details.item_id where orders.total_price #{sign} #{total} group by orders.id ")
    end

    def self.show_all_by_range_date(date_start,date_end)
        find_by_sql("select orders.* , GROUP_CONCAT(items.name || ' - ' || cast(order_details.quantity as varchar) || ' portion / Rp.' || cast(order_details.price as varchar), ' | '  ) as detail from orders left join order_details on orders.id = order_details.order_id left join items on items.id = order_details.item_id where DATE(orders.created_at) between '#{date_start}' and '#{date_end}' group by orders.id ")
    end

    def self.find_join(id)
        find_by_sql("select orders.* , GROUP_CONCAT(items.name || ' - ' || cast(order_details.quantity as varchar) || ' portion / Rp.' || cast(order_details.price as varchar), ' | '  ) as detail from orders left join order_details on orders.id = order_details.order_id left join items on items.id = order_details.item_id where orders.id = #{id}")
    end

    def self.get_item_order(id)
        find_by_sql("select items.name, items.id, order_details.quantity, order_details.price from order_details inner join orders on orders.id = order_details.order_id inner join items on items.id = order_details.item_id where orders.id = #{id}")
    end

    def self.update_total_price(order_id)
        update_prices = find_by_sql("select SUM(price*quantity) as total_price from order_details where order_id = #{order_id}").first
        order = Order.find_by(id: order_id)
        order.update(total_price: update_prices[:total_price])
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  before_action :set_order, only: %i[ edit update destroy ]
  before_action :set_item, only: %i[ new edit ]
  before_action :set_status, only: %i[ index ]


  # GET /orders or /orders.json
  def index
    if params[:email]
      @orders = Order.show_all_by_email(params[:email])
    elsif params[:today]
      @orders = Order.show_all_by_today(params[:today])
    elsif params[:total_price]
      @orders = Order.show_all_by_total_price(params[:total_price], params[:sign])
    elsif params[:date_start]
      @orders = Order.show_all_by_range_date(params[:date_start], params[:date_end])
    else
      @orders = Order.show_all
    end
  end

  # GET /orders/1 or /orders/1.json
  def show
    @order = Order.find_join(params[:id])
    if @order[0][:id] == nil
      render_404
    end
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
    @item_orders = Order.get_item_order(params[:id])
    if @order[:status_order] == 0
      current_items_order_id = OrderDetail.where(order_id: params[:id]).map(&:item_id)
      notyet_items_order_id =[]
      notyet_items_name = []
      notyet_items_price = []
  
      @items.each do |item|
        if current_items_order_id.include?(item.id) == false
          notyet_items_order_id << item.id
          notyet_items_name << item.name
          notyet_items_price << item.price 
        end
      end
  
      @notyet_item_orders = notyet_items_order_id.zip(notyet_items_name, notyet_items_price)
    else
      redirect_to orders_path, notice: "Order cannot edit because it's already PAID / CANCELED"
    end
  end

  # POST /orders or /orders.json
  def create
    @total_price = 0
    email = params[:order][:email]
    if valid_email?(email)
      @order_items = params[:item]
      if !@order_items.nil?
        @order = Order.create(email: email, status_order: 0)
        @order_items.each do |order_item|
            price_item = Item.select(:price).where(id: order_item).first
            quantity = params["quantity_"+order_item]
            @total_price = @total_price + (price_item[:price] * quantity.to_f)
            new_order_detail = OrderDetail.new(order_id: @order.id, item_id: order_item, price: price_item[:price], quantity: quantity.to_i)
            new_order_detail.save
        end      
        @order.total_price = @total_price
      end
      respond_to do |format|
        if @order_items.nil?
          format.html { redirect_to orders_path, notice: "Unsucessfully process. Order must have 1 item order" }
        elsif @order.save
          format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
          format.json { render :show, status: :created, location: @order }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @order.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to new_order_path, notice: "Unsucessfully process. Use Email Valid"
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    @order.email = params[:order][:email]
    @order.status_order = params[:order][:status_order]
    respond_to do |format|
      if @order.save
        if params[:item] != nil
          item_orders = params[:item]
          item_orders.each do |item|
            quantity = params["quantity_"+item]
            order_detail = OrderDetail.update_item_order(params[:id],item,quantity)
          end
        end
        @order2 = OrderDetail.find_by(order_id: params[:id])
        if @order2.nil?
          order = Order.find_by(id: params[:id])
          order.destroy
          format.html { redirect_to orders_path, notice: "Order was successfully destroyed." }
        else
          format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
          format.json { render :show, status: :ok, location: @order }
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    order_detail = OrderDetail.where(order_id: params[:id])
    order_detail.destroy_all  
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    def set_item
      @items = Item.all
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:email, :status_order, :total_price)
    end

    def render_404
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end

    def valid_email?(email)
      valid_email = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      email =~ valid_email
    end


    def set_status
      current_datetime = DateTime.current.localtime
      orders = Order.all

      orders.each do |order|
        date_order = order.created_at.localtime
        order_time = Time.parse(date_order.strftime('%H:%M:%S'))
        current_time = Time.parse(current_datetime.strftime('%H:%M:%S'))
        if current_time.hour > 16 
          if date_order.to_date == current_datetime.to_date
            if order_time.hour < 17  && order.status_order == 0
              update_status = Order.find(order.id)
              update_status.status_order = 2
              update_status.save
            end
          else
            tommorow_date_order = date_order.days_since(1)
            if tommorow_date_order.to_date == current_datetime.to_date
              if order.status_order == 0
                update_status = Order.find(order.id)
                update_status.status_order = 2
                update_status.save
              end
            end
          end
        end
      end

    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>
      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <%= link_to "Try Again", new_order_path, {class: "btn btn-info mt-3"} %>
  <% else %>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.email_field :email, {class: "form-control", placeholder: "Insert Email Customer", required: true}  %>
    </div>
    <% if order.status_order %>
      <div class="form-group">
        <%= form.label :status_order, style: "display: block" %>
        <%= form.select(:status_order, [['NEW',0], ['PAID',1], ['CANCELED',2]], {selected: order.status_order},  {class: "form-control"}) %>
      </div>
    <% end %>
    <div>
      <p class="mt-3 mb-0" >List Menus</p>
      <% if @item_orders %>
        <p class="m-t-10 fw-bold" style="color:green;">Ordered Menu</p>
        <% @item_orders.each do |item| %>
          <div class="form-check m-t-10">
            <input class="form-check-input" type="checkbox" id="<%= item.name %>" name="item[]" value="<%= item.id %>" checked>
            <label class="form-check-label" for="<%= item.name %>"><%= item.name %> - Rp.<%= item.price %>/portion</label>
            <input class="form-control" type="number" name="quantity_<%= item.id %>" placeholder="how many do you order ?" value="<%= item.quantity %>">
            <small>fill quantity with 0 if order was canceled</small>
          </div>
        <% end %>
        <% if !@notyet_item_orders.empty? %>
          <p class="m-t-10 fw-bold" style="color:red;" >Unordered Menu</p>
          <% @notyet_item_orders.each do |id, name, price| %>
            <div class="form-check m-t-10">
              <input class="form-check-input" type="checkbox" id="<%= name %>" name="item[]" value="<%= id %>">
              <label class="form-check-label" for="<%= name %>"><%= name %> - Rp.<%= price %>/portion</label>
              <input class="form-control" type="number" name="quantity_<%= id %>" placeholder="how many do you order ?">
              <small>checklist and fill quantity if you choose this</small>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <% @items.each do |item| %>
          <div class="form-check m-t-10">
            <input class="form-check-input" type="checkbox" id="<%= item.name %>" name="item[]" value="<%= item.id %>">
            <label class="form-check-label" for="<%= item.name %>"><%= item.name %> - Rp.<%= item.price %>/portion</label>
            <input class="form-control" type="number" name="quantity_<%= item.id %>" placeholder="how many do you order ?">
            <small>checklist and fill quantity if you choose this</small>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="mt-4">
      <%= form.submit 'Save', :class => 'btn btn-success'%>
      <%= link_to "Back to orders", orders_path, {class: "btn btn-secondary ms-2"} %>
    </div>
  <% end %>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <h5 class="card-title mb-3">Status Order : 
    <% status = ["NEW","PAID","CANCELED"] %>
    <%= status[order.status_order] %>
  </h5>
  <p class="card-text"> Order Date : <%= order.created_at.localtime.strftime('%a, %d %b %Y %H:%M:%S WIB') %></p>
  <p class="card-text"> Detail Order : <%= order.detail %></p>
  <p class="card-text"> Total Price : Rp. <%= order.total_price %></p>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>
<div class="mt-3">
  <%= link_to "Show this order", @order, {class: "btn btn-primary"} %>
</div>
<div class="form">
  <%= render "form", order: @order %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>List Orders</h1>
<%= @order_times %>
<%= @current_times %>
<div class="mt-3">
  <%= link_to "Dashboard", '/',  {class: "btn btn-secondary"} %>
  <%= link_to "New order", new_order_path,  {class: "btn btn-success"} %>
</div>
<h4 class="mt-3">Daily Report</h4>
<div class="mt-3">
  <%= link_to "Show All", orders_path,  {class: "btn btn-cus"} %>
  <%= link_to "Show Order Today", "/orders?today=#{DateTime.current.to_date}",  {class: "btn btn-cus"} %>
  <a class="btn btn-cus" href="javascript:void(0)" data-bs-toggle="modal" data-bs-target="#filterEmail">Filter With Email</a>
  <a class="btn btn-cus" href="javascript:void(0)" data-bs-toggle="modal" data-bs-target="#filterPrice">Filter With Total Price</a>
  <a class="btn btn-cus" href="javascript:void(0)" data-bs-toggle="modal" data-bs-target="#filterDate">Filter With Date</a>
  <div class="modal fade" id="filterEmail" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content bg-secondary">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Display List Order With Email</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="">
            <div class="mb-3">
              <label for="email" class="form-label">Email Customer</label>
              <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Insert Email Customer" name="email" required>
            </div>
            <button type="submit" class="btn btn-cus">Filter</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="filterPrice" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content bg-secondary">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Display List Order With Total Price</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="">
            <div class="mb-3">
              <label for="total_price" class="form-label">Total Price</label>
              <input type="total_price" class="form-control" id="total_price" placeholder="Insert Total Price Order" name="total_price" required>
            </div>
            <div class="mb-3">
              <label class="form-label">Choose assign</label>
              <select class="form-select" name="sign">
                <option value="=">Equal</option>
                <option value="<=">Less Than</option>
                <option value=">=">More Than</option>
              </select>
            </div>
            <button type="submit" class="btn btn-cus">Filter</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="filterDate" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content bg-secondary">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Display List Order With Date</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="">
            <div class="mb-3">
              <label for="date_start" class="form-label">Date Start</label>
              <input type="date" class="form-control" id="date_start" placeholder="Insert Total Price Order" name="date_start" required>
            </div>
            <div class="mb-3">
              <label for="date_end" class="form-label">Date End</label>
              <input type="date" class="form-control" id="date_end" placeholder="Insert Total Price Order" name="date_end" required>
            </div>
            <button type="submit" class="btn btn-cus">Filter</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="orders">
  <div class="row">
    <% @orders.each do |order| %>
      <div class="col-sm-4 mt-5">
        <div class="card">
          <div class="card-header">
            Email Customer : <%= order.email %>
          </div>
          <div class="card-body">
            <%= render order %>
          </div>
          <div class="card-footer text-end">
            <%= link_to "Show this order", order,  {class: "btn card-button"} %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<p style="color: green"><%= notice %></p>
<h1>New order</h1>
<div class="form">
  <%= render "form", order: @order %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>
<h1>Detail Order</h1>
<%= link_to "Back to orders", orders_path, {class: "btn btn-secondary mt-3 mb-3"} %>
<div class="card">
  <div class="card-header">
    Email Customer : <%= @order[0][:email]%>
  </div>
  <div class="card-body">
    <%= render @order %>
  </div>
  <div class="d-flex card-footer">
    <% if @order[0][:status_order] == 0 %>
      <%= link_to "Edit this order", edit_order_path(@order), {class: "btn card-button me-3"} %>
    <% end %>
    <%= button_to "Destroy this order", @order, method: :delete, class: "btn btn-danger" %>
  </div>
</div>