config/routes.rb
Rails.application.routes.draw do
  get '/' => "home#index"
  resources :orders
  resources :categories
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/item.rb
class Item < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validates :description, presence: true, length: { maximum: 150, too_long: "%{count} characters is the maximum allowed" }
    validates :price, presence: true, numericality: {greater_than_or_equal_to: 0.01}

    def self.show_all
        find_by_sql("select items.*, GROUP_CONCAT(categories.name) as category from items left join item_categories on item_id = items.id left join categories on categories.id = category_id group by items.id ")
    end

    def self.find_join(id)
        find_by_sql("select items.*, GROUP_CONCAT(categories.name) as category from items left join item_categories on item_id = items.id left join categories on categories.id = category_id where items.id = #{id} group by items.id ")
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :set_category, only: %i[ new edit ]

  # GET /items or /items.json
  def index
    @items = Item.show_all
  end

  # GET /items/1 or /items/1.json
  def show
    @item = Item.find_join(params[:id])
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    @current_categories = ItemCategory.get_current_category(params[:id])
    current_categories_id = ItemCategory.where(item_id: params[:id]).map(&:category_id)
    notyet_categories_id =[]
    notyet_categories_name = []

    @categories.each do |category|
      if current_categories_id.include?(category.id) == false
        notyet_categories_id << category.id
        notyet_categories_name << category.name      
      end
    end

    @notyet_categories = notyet_categories_id.zip(notyet_categories_name)
    
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        if params[:category]
          categories = params[:category]
          categories.each do |category|
            ItemCategory.create(item_id: @item.id, category_id: category)
          end
        end
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        if params[:category] != nil
          categories = params[:category]
          categories.each do |category|
            ItemCategory.update_item_category(params[:id],category)
          end 
        end
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    
    item_category = ItemCategory.where(item_id: params[:id])
    item_category.destroy_all

    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def set_category
      @categories = Category.all
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :description, :price)
    end

    def render_404
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <%= link_to "Try Again", new_item_path, {class: "btn btn-info mt-3"} %>
  <% else %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, {class: "form-control", placeholder: "Insert Item Name", required: true}  %>
    </div>
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, {class: "form-control", placeholder: "Insert Item Description", required: true, rows: "5"}  %>
    </div>
    <div class="form-group">
      <%= form.label :price %>
      <%= form.number_field :price, {class: "form-control", placeholder: "Insert Item Price", required: true}  %>
    </div>
    <div>
      <p class="mt-3 mb-0">Category</p>
      <% if @current_categories %>
        <div class="row">
          <% @current_categories.each do |category| %>
            <div class="col-sm-4 mt-3">
              <input class="form-control" type="text" value="<%= category.name %>" disabled>
            </div>
          <% end %>
        </div>
        <p class="m-t-10 fw-bold" style="color:red;">Delete Category</p>
        <small class="text-muted">checklist category you want to delete</small>
        <div class="mt-2">
          <% @current_categories.each do |category| %>
            <div class="form-check">
              <input class="form-check-input" type="checkbox" id="<%= category.name %>" name="category[]" value="<%= category.id %>">
              <label class="form-check-label" for="<%= category.name %>">
                <%= category.name %>
              </label>
            </div>
          <% end %>
        </div>
      <% end %>
      <% if !@notyet_categories %>
        <small class="text-muted">checklist category related to item</small>
        <div class="mt-2">
          <% @categories.each do |category| %>
            <div class="form-check">
              <input class="form-check-input" type="checkbox" id="<%= category.name %>" name="category[]" value="<%= category.id %>">
              <label class="form-check-label" for="<%= category.name %>">
                <%= category.name %>
              </label>
            </div>
          <% end %>
        </div>
      <% elsif !@notyet_categories.empty? %>
        <p class="m-t-10 fw-bold" style="color:green;">Add Category</p>
        <small class="text-muted">checklist category you want to add</small>
        <div class="mt-2">
          <% @notyet_categories.each do |id, name| %>
            <div class="form-check">
              <input class="form-check-input" type="checkbox" id="<%= name %>" name="category[]" value="<%= id %>">
              <label class="form-check-label" for="<%= name %>">
                <%= name %>
              </label>
            </div>
          <% end %>
        </div>
      <% end %>
      <%= link_to "Create New Category", new_category_path, {class: "btn btn-info text-uppercase mt-3", style: "font-size:10px;"} %>
    </div>
    <div class="mt-4">
      <%= form.submit 'Save', :class => 'btn btn-success'%>
      <%= link_to "Back to items", items_path, {class: "btn btn-secondary ms-2"} %>
    </div>
  <% end %>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <h5 class="card-title mb-3">Rp.<%= item.price %> / portion</h5>
  <p class="card-text">
    Category : 
    <% if item.category.nil? %>
      -
    <% else %>
      <%= item.category %>
    <% end %>
  </p>
  <p class="card-text">Description : <%= item.description %></p>
</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>
<div class="mt-3">
  <%= link_to "Show this item", @item, {class: "btn btn-primary"} %>
</div>
<div class="form">
  <%= render "form", item: @item %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Item Menus</h1>
<div class="mt-3">
  <%= link_to "Dashboard", '/',  {class: "btn btn-secondary"} %>
  <%= link_to "New item", new_item_path,  {class: "btn btn-success"} %>
</div>
<div id="items">
  <div class="row">
    <% @items.each do |item| %>
      <div class="col-sm-4 mt-5">
        <div class="card">
          <div class="card-header">
            Item Name : <%= item.name.capitalize %>
          </div>
          <div class="card-body">
            <%= render item %>
          </div>
          <div class="card-footer text-end">
            <%= link_to "Show this item", item,  {class: "btn card-button"} %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<h1>New item</h1>
<div class="form">
  <%= render "form", item: @item %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>
<h1>Detail Item</h1>
<%= link_to "Back to items", items_path, {class: "btn btn-secondary mt-3 mb-3"} %>
<div class="card">
  <div class="card-header">
    Item Name : <%= @item[0][:name].capitalize %>
  </div>
  <div class="card-body">
    <%= render @item %>
  </div>
  <div class="d-flex card-footer">
    <%= link_to "Edit this item", edit_item_path(@item), {class: "btn card-button me-3"} %>
    <%= button_to "Destroy this item", @item, method: :delete, class: "btn btn-danger" %>
  </div>
</div>
<div>
</div>