config/routes.rb
Rails.application.routes.draw do
  get '/' => "home#index"
  resources :orders
  resources :categories
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  before_action :set_category, only: %i[edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: "Category was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: "Category was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end

    def render_404
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, {class: "form-control", placeholder: "Insert category Name", required: true}  %>
    </div>
  </div>
  <div class="mt-3">
    <%= form.submit 'Save', :class => 'btn btn-success'%>
    <%= link_to "See List categories", categories_path, {class: "btn btn-primary"} %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>
<div class="form">
  <%= render "form", category: @category %>
</div>
<br>
<div>
  <%= link_to "Cancel", :back, {class: "btn btn-secondary"} %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>List Categories</h1>
<div class="mt-3">
  <%= link_to "Back to menu", '/items',  {class: "btn btn-secondary"} %>
  <%= link_to "New Category", new_category_path,  {class: "btn btn-success"} %>
</div>
<div class="mt-3">
  <table class="table table-bordered table-custom">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">Name</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each_with_index do |category, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= category.name %></td>
          <td>
            <div class="d-flex">
              <%= link_to "edit", edit_category_path(category), {class: "btn btn-info me-3", style: "font-size:10px;" } %>
              <%= button_to "delete", category, method: :delete, class: "btn btn-danger", style: "font-size:10px;" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>
<div class="form">
  <%= render "form", category: @category %>
</div>
<br>
<div>
  <%= link_to "Back to items", items_path, {class: "btn btn-secondary"} %>
</div>